export { default as ComparisonPage } from "./Comparison";
export { default as Dashboard } from "./Dashboard";
export { default as Login } from "./Login";
export { default as MarketCapPage } from "./MarketCap";
export { default as Profile } from "./Profile";
export { default as Register } from "./Register";
export { default as SettingsPage } from "./Settings";
export { default as SignalsPage } from "./Signals";
export { default as Unauthorized } from "./Unauthorized";
